// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewUser struct {
	FullName string `json:"fullName"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type User struct {
	UserID    string `json:"userId"`
	FullName  string `json:"fullName"`
	Email     string `json:"email"`
	Password  string `json:"password"`
	CreatedAt int    `json:"createdAt"`
	UpdatedAt int    `json:"updatedAt"`
}

